name: Sync to Gitee

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/Cy-xin/image-bed.git"
          destination-repo: "https://gitee.com/${{ secrets.GITEE_USERNAME }}/image-bed.git"
          username: "${{ secrets.GITEE_USERNAME }}"
          password: "${{ secrets.GITEE_TOKEN }}"
